const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ItemTrnSchema = new Schema(
  {
    pcode: { type: String },
    pname: { type: String },
    itemcode: { type: String },
    itemname: { type: String },
    against_bill_no: { type: String },
    auto_bill_nos: { type: String },
    group_code: { type: String },
    group_name: { type: String },
    bill_no: { type: String },
    bill_date: { type: String },
    bill_time: { type: String },
    iss_qty: { type: String },
    rec_qty: { type: String },
    qty_trn: { type: String },
    rate_trn: { type: String },
    amt_trn: { type: String },
    sub_tot1: { type: String },
    dis_per: { type: String },
    dis_amt: { type: String },
    gross_tot1: { type: String },
    tax_code: { type: String },
    tax_name: { type: String },
    taxper: { type: String },
    tax_amt: { type: String },
    net_amt: { type: String },
    tot_qty: { type: String },
    rec_type: { type: String },
    ir_flag: { type: String },
    vou_type: { type: String },
    ref_1: { type: String },
    qty_remark: { type: String },
    bill_date_time: { type: String },
    username: { type: String },
    nag_qty: { type: String },
    bag_qty: { type: String },
    loose_qty: { type: String },
    packing_type: { type: String },
    cartage_amt: { type: String },
    delivery_date: { type: String },
    form_yn: { type: String },
    form_no: { type: String },
    form_type: { type: String },
    bt_amt: { type: String },
    veh_no: { type: String },
    station_name: { type: String },
    transport_name: { type: String },
    gr_rr_no: { type: String },
    fraight: { type: String },
    ordno: { type: String },
    ord_date: { type: String },
    ch_no: { type: String },
    ch_date: { type: String },

    pkg_wgt: { type: String },
    rnd_off_amt: { type: String },
    dis_per_2: { type: String },
    dis_amt_2: { type: String },
    all_dis_tot: { type: String },
    hsn_code: { type: String },
    gst_type: { type: String },
    state_code: { type: String },
    cartage_per: { type: String },
    igst_per: { type: String },
    igst_amt: { type: String },
    sgst_per: { type: String },
    sgst_amt: { type: String },
    cgst_per: { type: String },
    cgst_amt: { type: String },
    reverse_charge: { type: String },
    electronic_ref_no: { type: String },
    bill_no_numric: { type: String },
    sub_tot_1st_trn: { type: String },
    dis_per_1st: { type: String },
    dis_amt_1st: { type: String },
    dis_amt_1st_tot: { type: String },
    rate_after_dis_1st: { type: String },
    sub_tot_2nd_trn: { type: String },
    dis_per_2nd: { type: String },
    dis_amt_2nd: { type: String },
    dis_amt_2nd_tot: { type: String },
    rate_after_dis_2nd: { type: String },
    sub_tot_3rd_trn: { type: String },
    f_rate_trn: { type: String },
    gst_per_trn: { type: String },
    gst_amt_on_f_rate_trn: { type: String },
    gst_amt_tot_trn: { type: String },
    rate_after_gst: { type: String },
    site_add_yn: { type: String },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('ItemTrn', ItemTrnSchema);
